# Generated by Django 2.0.5 on 2018-09-24 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('adresse1', models.CharField(max_length=200)),
                ('adresse2', models.CharField(blank=True, max_length=200, null=True)),
                ('adresse3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('anneescolaire', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedebut', models.DateTimeField()),
                ('datefin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursGroupes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Cours')),
            ],
        ),
        migrations.CreateModel(
            name='CoursSalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Cours')),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.AnneeScolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.Diplome')),
            ],
        ),
        migrations.CreateModel(
            name='FiliereEleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GroupesEnseignants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('datedebut', models.DateTimeField()),
                ('datefin', models.DateTimeField()),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.Diplome')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('batiment', models.CharField(blank=True, max_length=200, null=True)),
                ('capacite', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('descriptif', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UEFilieres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Filiere')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.UE')),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bo.Personne')),
            ],
            bases=('bo.personne',),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bo.Personne')),
            ],
            bases=('bo.personne',),
        ),
        migrations.AddField(
            model_name='ue',
            name='filieres',
            field=models.ManyToManyField(through='bo.UEFilieres', to='bo.Filiere'),
        ),
        migrations.AddField(
            model_name='ue',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.Periode'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.UE'),
        ),
        migrations.AddField(
            model_name='courssalles',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Salle'),
        ),
        migrations.AddField(
            model_name='coursgroupes',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Groupe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='groupes',
            field=models.ManyToManyField(through='bo.CoursGroupes', to='bo.Groupe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='salles',
            field=models.ManyToManyField(through='bo.CoursSalles', to='bo.Salle'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Personne'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.Eleve'),
        ),
        migrations.AddField(
            model_name='groupesenseignants',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.Enseignant'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='enseignants',
            field=models.ManyToManyField(through='bo.GroupesEnseignants', to='bo.Enseignant'),
        ),
        migrations.AddField(
            model_name='filiereeleve',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Eleve'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='filiere',
            field=models.ManyToManyField(through='bo.FiliereEleve', to='bo.Filiere'),
        ),
    ]
