# Generated by Django 2.0.5 on 2018-11-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiereeleve',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.Eleve'),
        ),
        migrations.AlterField(
            model_name='filiereeleve',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.Filiere'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.UE'),
        ),
        migrations.AlterField(
            model_name='uefilieres',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.Filiere'),
        ),
        migrations.AlterField(
            model_name='uefilieres',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bo.UE'),
        ),
    ]
