# Generated by Django 2.0.5 on 2018-11-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0009_historicaladresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiereeleve',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Eleve'),
        ),
        migrations.AlterField(
            model_name='filiereeleve',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Filiere'),
        ),
    ]
