# Generated by Django 2.0.5 on 2018-11-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0011_absence_devoir_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='note',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='bareme',
        ),
        migrations.AddField(
            model_name='cours',
            name='duplication',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devoir',
            name='type',
            field=models.CharField(choices=[('EXO', 'Exercices'), ('ORA', 'Oral')], default='EXO', max_length=3),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
