# Generated by Django 2.0.5 on 2018-11-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0012_auto_20181128_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='duplication',
        ),
    ]
