# Generated by Django 2.0.5 on 2018-12-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0014_devoir_texte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXO', 'Ecrit'), ('ORA', 'Oral')], default='EXO', max_length=3)),
                ('bareme', models.IntegerField(default=20)),
                ('classant', models.BooleanField(default=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bo.Cours')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(blank=True, default=None, null=True)),
                ('absence', models.BooleanField(default=False)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Controle')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bo.Eleve')),
            ],
        ),
    ]
