# Generated by Django 2.0.5 on 2018-12-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0016_auto_20181212_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
