# Generated by Django 2.1.7 on 2019-03-29 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0017_auto_20181212_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaleleve',
            name='personne_ptr',
            field=models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='bo.Personne'),
        ),
        migrations.AlterField(
            model_name='historicalenseignant',
            name='personne_ptr',
            field=models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='bo.Personne'),
        ),
    ]
